### ISSUE TITLE
[Docker Model] Struct destroy the .yml insert

### ISSUE THREAD

**Issue by guidiego** [purrgil/purrgil#2]
In this [source](https://github.com/guidiego/purrgil/blob/master/models/docker.go#L14) I have a simple struct:

```golang
type DockerComposeServices struct {
    Build      string    `yaml:"build"`
    Image      string    `yaml:"image"`
    Command    string    `yaml:"command"`
    Ports      []string  `yaml:"ports"`
    Volumes    []string  `yaml:"volumes"`
    DependsOn  []string  `yaml:"depends_on"`
}
```

The problem is, Image and Build can't be in the same object, sometime we don't have ports, command, volumes and other compose things, I need to create a dynamic way to mount that. I read something about polymorfism with if validantions, but not get the point yet :D

**Comment by rdeusser** [comment]
Add `omitempty` to the yaml tags. So like this:
```go
type DockerComposeServices struct {
    Build      string    `yaml:"build,omitempty"`
    Image      string    `yaml:"image,omitempty"`
    Command    string    `yaml:"command,omitempty"`
    Ports      []string  `yaml:"ports,omitempty"`
    Volumes    []string  `yaml:"volumes,omitempty"`
    DependsOn  []string  `yaml:"depends_on,omitempty"`
}
```

**Comment by guidiego** [comment]
Thx for helping @iamthemuffinman, I fix it in the last commit <3
